# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a71c06bae1de1d82f3d544cc789f2c1c7846366e6dfa9910b849c81769f6d4fdf2487fc7600954dd81e0c8d3ff08151baa422ce90386d8e430c84cd1d42a1274

test:
  secret_key_base: c0bbde756544b2fe0925ee3779a7173708b9d82bf1b04b4bb789978650917a8d63f3a1c2a36840be8b48270481226cb9b202b1036b93af14499d644d97cfed15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
